### PR TITLE
[WIP] Fix OpenMP on Windows

### PR DESCRIPTION
**Pull request by ax3l**
Working on https://github.com/AMReX-Codes/amrex/issues/3795

- [x] run OpenMP tests
- [ ] try https://github.com/AMReX-Codes/amrex/pull/3910

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
So strange that the OpenMP tests pass here but not in a dependent repo:
```
(%BUILD_PREFIX%) %SRC_DIR%>ctest --test-dir build --build-config Release --output-on-failure -R OpenMP 
Internal ctest changing into directory: D:/bld/amrex_1714368890030/work/build
Test project D:/bld/amrex_1714368890030/work/build
    Start 105: OpenMP_atomicAdd_1d
1/3 Test #105: OpenMP_atomicAdd_1d ..............   Passed    0.06 sec
    Start 106: OpenMP_atomicAdd_2d
2/3 Test #106: OpenMP_atomicAdd_2d ..............   Passed    0.03 sec
    Start 107: OpenMP_atomicAdd_3d
3/3 Test #107: OpenMP_atomicAdd_3d ..............   Passed    0.08 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =   0.23 sec
```

**Comment by ax3l** [comment]
@isuruf I am installing the import lib `.lib` into `bin/` while installing the `.dll` into `lib/` ... is that a problem?
```
2024-04-29T06:01:10.1934787Z -- Installing: D:/bld/amrex_1714368890030/_h_env/Library/lib/amrex_3d.lib
2024-04-29T06:01:10.2011064Z -- Installing: D:/bld/amrex_1714368890030/_h_env/Library/bin/amrex_3d.dll
```
https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#why-does-find_library-not-find-dll-libraries-under-win32

**Comment by isuruf** [comment]
> I am installing the AMReX import libs amrex_*.lib into lib/ while installing the dynamic symbols amrex_*.dll into bin/ ... is that a problem?

Nope

**Comment by ax3l** [comment]
I noticed that I cannot find a symbol for `omp_lock_t` in neither `libiomp5md.dll` nor `libomp.dll` of the conda-forge [llvm-openmp](https://anaconda.org/conda-forge/llvm-openmp/files) package...

**Comment by isuruf** [comment]
Types don't have symbols in dynamic libraries. Only functions and global data variables.

**Comment by ax3l** [comment]
I'll try patching in https://github.com/AMReX-Codes/amrex/pull/3910 to the 24.05 release.

**Comment by ax3l** [comment]
In parallel, I contributed to CMake 3.30+ the support for OpenMP from LLVM in MSVC (instead of Clang-Cl), which we can try as well once released: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9475

**Comment by ax3l** [comment]
Testing the patch for the 24.05 release via #24

**Comment by ax3l** [comment]
Patch in upstream for 24.05+

**Pull request closed without merging**
